# Site Info
title:              "thtrieu"
description:        "minimum"
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Logos
logos: 
  rock:     "http://i.imgur.com/f7b0EjX.gif" #
  daisy:    "http://i.imgur.com/ygEHnz5.gif" #
  flower:   "http://i.imgur.com/JX9gCsP.gif"
  coffee:   "http://i.imgur.com/d3GJwO1.gif"
  spoon:    "http://i.imgur.com/6UaSYA9.gif"
  pooring:  "http://i.imgur.com/0TNlsRx.gif"
  smoke:    "http://i.imgur.com/wUl8kal.gif"
  step1:    "http://i.imgur.com/LVF0HOR.gif"
  step2:    "http://i.imgur.com/FCePkA4.gif"
  christ:   "http://i.imgur.com/iqDJCdf.gif"
  touch:    "http://i.imgur.com/f19wdua.gif"
  pure:     "http://i.imgur.com/RDbvdeg.gif"
  bookafe:  "http://i.imgur.com/1NngOKZ.gif"
  purer:    "http://i.imgur.com/l1tA8nA.gif"
  spike:    "http://i.imgur.com/P5Ifo0E.gif" #
  moss:     "http://i.imgur.com/JNoDa9E.gif"
  drip:     "http://i.imgur.com/hbaEn2i.gif" #
  surface:  "http://i.imgur.com/2zsgYDR.gif"
  fly:      "http://i.imgur.com/tU08Pu4.gif" #
  wood:     "http://i.imgur.com/w6NOJp2.gif" #

# Author Info
author_name:        "thtrieu"
author_email:       thtrieu@apcs.vn
author_host:        ".github.io/"

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Asia/Ho_Chi_Minh # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
markdown:           redcarpet
redcarpet:
   extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
