# Site Info
title:              "thtrieu"
description:        "minimum"
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Logos
logos: 
  rock:     "http://i.imgur.com/CVBp6Yp.gif" # rock
  daisy:    "http://i.imgur.com/tejvnIK.gif" # daisy
  coffee:   "http://i.imgur.com/d3GJwO1.gif" # coffee
  spoon:    "http://i.imgur.com/6UaSYA9.gif" # spoon
  pooring:  "http://i.imgur.com/0TNlsRx.gif" # pooring
  smoke:    "http://i.imgur.com/wUl8kal.gif" # smoke
  step1:    "http://i.imgur.com/LVF0HOR.gif" # step1
  step2:    "http://i.imgur.com/FCePkA4.gif" # step2
  christ:   "http://i.imgur.com/iqDJCdf.gif" # christ
  touch:    "http://i.imgur.com/f19wdua.gif" # touch

# Author Info
author_name:        "thtrieu"
author_email:       thtrieu@apcs.vn

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Asia/Ho_Chi_Minh # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
markdown:           redcarpet
redcarpet:
   extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
